language: python
python:
    - 2.7

install:
    - pip install -r tests/requirements/py2.txt
    - pip install coveralls

script:
    - cd tests
    - PYTHONPATH=..:$PYTHONPATH ./runtests.py
    
after_success:
    coveralls

