language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4

install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r tests/requirements/py2.txt
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r tests/requirements/py3.txt
    - pip install coveralls

script:
    - cd tests
    - PYTHONPATH=..:$PYTHONPATH ./runtests.py

after_success:
    coveralls

