language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4

install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r tests/requirements/py2.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r tests/requirements/py3.txt; fi
    - pip install coveralls

script:
    - cd tests
    - PYTHONPATH=..:$PYTHONPATH coverage run ./runtests.py --settings=test_sqlite

after_success:
    coveralls

